### ISSUE TITLE
Create a version of the JupoyterLite site for use in Moodle

### ISSUE THREAD

**Issue by psychemedia** [ouseful-testing/jupyterlite-webr-kernel#3]
Various patches are required to get a JupyterLite site to work as an embedded site in Moodle VLE (eg [docs](https://opencomputinglab.github.io/jupyterlite_in_moodle_vle/deployment_notes.html)).

Modify the action to create a build:

- with updated manifiest link:

```yaml
      - name: Patch JupyterLite for Moodle use
        run: |
          sed -i 's|<link rel="manifest" href="\([^"]*\)" />|<link rel="manifest" href="\1" crossorigin="use-credentials" />|' ./_output/lab/index.html

Use a patched `config-utils.js` file that includes a URL argument stripper:

```yaml
      - name: Patch config-utils.js
        run: cp ./patches/config-utils.js ./_output/config-utils.js
```
